CREATE TABLE `tbl_accounts` (
  `ACCOUNT_ID` int NOT NULL AUTO_INCREMENT,
  `ACCOUNT_NUMBER` varchar(18) NOT NULL,
  `ACCOUNT_BALANCE` decimal(20,2) NOT NULL,
  `CUSTOMER_ID` int NOT NULL,
  PRIMARY KEY (`ACCOUNT_ID`),
  KEY `TBL_ACCOUNTS_CUSTOMER_ID_1b13a23d_fk` (`CUSTOMER_ID`),
  CONSTRAINT `TBL_ACCOUNTS_CUSTOMER_ID_1b13a23d_fk` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `tbl_customer` (`CUSTOMER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2001 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
